name: Sync with Upstream
on: workflow_dispatch
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Sync
        run: |
          git config user.name "Brandon Tan"
          git config user.email "brandontan@gmail.com"
          git remote add upstream https://github.com/n8n-io/n8n-docs.git
          git fetch upstream
          git checkout master
          
          # Save our current workflow files
          cp -r .github/workflows /tmp/our_workflows
          
          # Pull all changes from upstream/main
          git pull upstream main --allow-unrelated-histories --strategy=recursive -X theirs
          
          # Remove the problematic workflow files from upstream
          rm -f .github/workflows/build-test.yml
          rm -f .github/workflows/lint.yml
          rm -f .github/workflows/lychee.yml
          rm -f .github/workflows/lychee-pr-check.yml
          rm -f .github/workflows/lexi.yml
          rm -f .github/workflows/support.yml
          
          # Restore our workflow files
          cp -r /tmp/our_workflows/* .github/workflows/
          
          # Stage and commit all changes
          git add -A
          
          # Only commit if there are changes
          if ! git diff --cached --quiet; then
            git commit -m "Sync with upstream: $(date) - removed problematic workflow files"
            git push origin master
            echo "✅ Successfully synced with upstream"
          else
            echo "ℹ️ No changes to sync"
          fi
