name: Sync with Upstream
on: workflow_dispatch
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Sync
        run: |
          git config user.name "Brandon Tan"
          git config user.email "brandontan@gmail.com"
          git remote add upstream https://github.com/n8n-io/n8n-docs.git
          git fetch upstream
          git checkout master
          
          # Reset to upstream/main but preserve our workflow files
          git checkout upstream/main -- .
          git checkout HEAD -- .github/workflows/
          
          # Commit and push the changes
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Sync with upstream: $(date)"
            git push origin master
          else
            echo "No changes to sync"
          fi
