name: Sync with Upstream
on: workflow_dispatch
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Sync
        run: |
          git config user.name "Brandon Tan"
          git config user.email "brandontan@gmail.com"
          git remote add upstream https://github.com/n8n-io/n8n-docs.git
          git fetch upstream
          git checkout master
          
          # Create a temporary branch for syncing
          git checkout -b sync-temp
          
          # Reset to upstream/main
          git reset --hard upstream/main
          
          # Remove problematic workflow files that cause permission issues
          rm -rf .github/workflows/build-test.yml
          rm -rf .github/workflows/lint.yml
          rm -rf .github/workflows/lychee.yml
          rm -rf .github/workflows/lychee-pr-check.yml
          rm -rf .github/workflows/lexi.yml
          rm -rf .github/workflows/support.yml
          
          # Restore our sync workflow
          git checkout master -- .github/workflows/blank.yml
          
          # Commit the sync
          git add -A
          git commit -m "Sync with upstream: $(date)" || echo "No changes to commit"
          
          # Switch back to master and merge
          git checkout master
          git merge sync-temp --strategy=ours -m "Merge sync changes"
          
          # Push the changes
          git push origin master
          
          # Cleanup
          git branch -d sync-temp
